### PR TITLE
Code sync with upstreaming effort

### LINKED ISSUE #54: Kernel Oops due to null pointer dereference
# The problem:
Connecting a LITE STAR GT978 FF racing wheel (with same quirks set manually as all the PXNs) causes the kernel to oops. Afterwards any process using `udev-worker` hangs on `read()` calls

Weirdly enough, force feedback works for a while - `ffcfstress` moves the wheel correctly, however after quitting the process, the wheel turns sharply max to the left.

Module installed manually via `make debug; insmod hid-universal-pidff.ko`, crashes on both linux and linux-zen arch kernels.

The steering wheel itself is available as Cobra GT987 FF in Poland

# uname output:
```
Linux hephaestos 6.12.10-arch1-1.1 #1 SMP PREEMPT_DYNAMIC Sun, 19 Jan 2025 16:05:58 +0000 x86_64 GNU/Linux
```

# dmesg output:
```
Jan 22 20:00:44 hephaestos kernel: usb 1-4: new full-speed USB device number 5 using xhci_hcd
Jan 22 20:00:44 hephaestos kernel: usb 1-4: New USB device found, idVendor=11ff, idProduct=2141, bcdDevice= 0.3d
Jan 22 20:00:44 hephaestos kernel: usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jan 22 20:00:44 hephaestos kernel: usb 1-4: Product: GT987 FF
Jan 22 20:00:44 hephaestos kernel: usb 1-4: Manufacturer: LITE STAR
Jan 22 20:00:44 hephaestos kernel: usb 1-4: SerialNumber: 511468687777
Jan 22 20:00:44 hephaestos kernel: input: LITE STAR GT987 FF as /devices/pci0000:00/0000:00:01.3/0000:06:00.0/usb1/1-4/1-4:1.0/0003:11FF:2141.0006/input/input25
Jan 22 20:00:44 hephaestos kernel: hid-generic 0003:11FF:2141.0006: unknown set_effect report layout
Jan 22 20:00:44 hephaestos kernel: hid-generic 0003:11FF:2141.0006: input,hidraw5: USB HID v1.11 Joystick [LITE STAR GT987 FF] on usb-0000:06:00.0-4/input0
Jan 22 20:00:44 hephaestos kernel: input: LITE STAR GT987 FF Keyboard as /devices/pci0000:00/0000:00:01.3/0000:06:00.0/usb1/1-4/1-4:1.1/0003:11FF:2141.0007/input/input26
Jan 22 20:00:44 hephaestos kernel: input: LITE STAR GT987 FF Mouse as /devices/pci0000:00/0000:00:01.3/0000:06:00.0/usb1/1-4/1-4:1.1/0003:11FF:2141.0007/input/input27
Jan 22 20:00:44 hephaestos kernel: hid-generic 0003:11FF:2141.0007: input,hidraw6: USB HID v1.10 Keyboard [LITE STAR GT987 FF] on usb-0000:06:00.0-4/input1
Jan 22 20:00:44 hephaestos kernel: input: LITE STAR GT987 FF as /devices/pci0000:00/0000:00:01.3/0000:06:00.0/usb1/1-4/1-4:1.0/0003:11FF:2141.0006/input/input28
Jan 22 20:00:44 hephaestos kernel: hid-universal-pidff 0003:11FF:2141.0006: input,hidraw5: USB HID v1.11 Joystick [LITE STAR GT987 FF] on usb-0000:06:00.0-4/input0
Jan 22 20:00:44 hephaestos kernel: hid-universal-pidff 0003:11FF:2141.0006: device has unknown autocenter control method
Jan 22 20:00:44 hephaestos kernel: input input28: Force feedback for USB HID PID devices
Jan 22 20:00:44 hephaestos kernel: BUG: kernel NULL pointer dereference, address: 0000000000000008
Jan 22 20:00:44 hephaestos kernel: #PF: supervisor read access in kernel mode
Jan 22 20:00:44 hephaestos kernel: #PF: error_code(0x0000) - not-present page
Jan 22 20:00:44 hephaestos kernel: PGD 0 P4D 0
Jan 22 20:00:44 hephaestos kernel: Oops: Oops: 0000 [#1] PREEMPT SMP NOPTI
Jan 22 20:00:44 hephaestos kernel: CPU: 2 UID: 0 PID: 5142 Comm: (udev-worker) Tainted: G           OE      6.12.10-arch1-1.1 #1 751339c66e88745afb6185fe3bce5dadf6985c3b
Jan 22 20:00:44 hephaestos kernel: Tainted: [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
Jan 22 20:00:44 hephaestos kernel: Hardware name: Micro-Star International Co., Ltd MS-7C02/B450 TOMAHAWK MAX (MS-7C02), BIOS 3.C0 01/11/2022
Jan 22 20:00:44 hephaestos kernel: RIP: 0010:universal_pidff_input_configured+0x26/0x80 [hid_universal_pidff]
Jan 22 20:00:44 hephaestos kernel: Code: 90 90 90 90 f3 0f 1e fa 0f 1f 44 00 00 55 45 31 c9 45 31 c0 53 48 8b 6e 18 31 f6 bb 01 00 00 00 48 8b 85 48 01 00 00 48 89 ef <8b> 48 08 8b 50 04>
Jan 22 20:00:44 hephaestos kernel: RSP: 0018:ffffa5668661b948 EFLAGS: 00010246
Jan 22 20:00:44 hephaestos kernel: RAX: 0000000000000000 RBX: 0000000000000001 RCX: ffff98b90bdf68a8
Jan 22 20:00:44 hephaestos kernel: RDX: ffff98b839ee1868 RSI: 0000000000000000 RDI: ffff98b90bdf6800
Jan 22 20:00:44 hephaestos kernel: RBP: ffff98b90bdf6800 R08: 0000000000000000 R09: 0000000000000000
Jan 22 20:00:44 hephaestos kernel: R10: 0000000000000000 R11: 0000000000000000 R12: ffff98ba08cec870
Jan 22 20:00:44 hephaestos kernel: R13: ffff98b839ee1840 R14: ffff98b839ee1840 R15: ffff98ba08cec000
Jan 22 20:00:44 hephaestos kernel: FS:  0000715fa38cb880(0000) GS:ffff98bb2ed00000(0000) knlGS:0000000000000000
Jan 22 20:00:44 hephaestos kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 22 20:00:44 hephaestos kernel: CR2: 0000000000000008 CR3: 000000036aba8000 CR4: 0000000000350ef0
Jan 22 20:00:44 hephaestos kernel: Call Trace:
Jan 22 20:00:44 hephaestos kernel:  <TASK>
Jan 22 20:00:44 hephaestos kernel:  ? __die_body.cold+0x8/0x12
Jan 22 20:00:44 hephaestos kernel:  ? page_fault_oops+0x15a/0x2e0
Jan 22 20:00:44 hephaestos kernel:  ? srso_return_thunk+0x5/0x5f
Jan 22 20:00:44 hephaestos kernel:  ? vsnprintf+0x52d/0x700
Jan 22 20:00:44 hephaestos kernel:  ? exc_page_fault+0x81/0x190
Jan 22 20:00:44 hephaestos kernel:  ? asm_exc_page_fault+0x26/0x30
Jan 22 20:00:44 hephaestos kernel:  ? universal_pidff_input_configured+0x26/0x80 [hid_universal_pidff 55b49ae4cd884535a75fc35c5a6e3d5760c319cb]
Jan 22 20:00:44 hephaestos kernel:  hidinput_connect+0x54b/0xd90
Jan 22 20:00:44 hephaestos kernel:  ? __kmalloc_noprof+0x189/0x400
Jan 22 20:00:44 hephaestos kernel:  hid_connect+0x3c3/0x610
Jan 22 20:00:44 hephaestos kernel:  ? srso_return_thunk+0x5/0x5f
Jan 22 20:00:44 hephaestos kernel:  hid_hw_start+0x40/0x70
Jan 22 20:00:44 hephaestos kernel:  universal_pidff_probe+0x2f/0x60 [hid_universal_pidff 55b49ae4cd884535a75fc35c5a6e3d5760c319cb]
Jan 22 20:00:44 hephaestos kernel:  ? hid_lookup_quirk+0x7b/0x1e0
Jan 22 20:00:44 hephaestos kernel:  hid_device_probe+0x111/0x1e0
Jan 22 20:00:44 hephaestos kernel:  really_probe+0xde/0x3b0
Jan 22 20:00:44 hephaestos kernel:  ? pm_runtime_barrier+0x54/0x90
Jan 22 20:00:44 hephaestos kernel:  ? __pfx___device_attach_driver+0x10/0x10
Jan 22 20:00:44 hephaestos kernel:  __driver_probe_device+0x78/0x110
Jan 22 20:00:44 hephaestos kernel:  driver_probe_device+0x1f/0x130
Jan 22 20:00:44 hephaestos kernel:  __device_attach_driver+0xbf/0x150
Jan 22 20:00:44 hephaestos kernel:  bus_for_each_drv+0x117/0x170
Jan 22 20:00:44 hephaestos kernel:  ? __pfx___hid_bus_reprobe_drivers+0x10/0x10
Jan 22 20:00:44 hephaestos kernel:  device_attach+0xed/0x120
Jan 22 20:00:44 hephaestos kernel:  device_reprobe+0x4e/0x90
Jan 22 20:00:44 hephaestos kernel:  ? __hid_bus_reprobe_drivers+0x3c/0x60
Jan 22 20:00:44 hephaestos kernel:  bus_for_each_dev+0x10e/0x170
Jan 22 20:00:44 hephaestos kernel:  ? __pfx___hid_bus_driver_added+0x10/0x10
Jan 22 20:00:44 hephaestos kernel:  __hid_bus_driver_added+0x2c/0x40
Jan 22 20:00:44 hephaestos kernel:  bus_for_each_drv+0x117/0x170
Jan 22 20:00:44 hephaestos kernel:  __hid_register_driver+0x74/0x80
Jan 22 20:00:44 hephaestos kernel:  ? __pfx_universal_pidff_init+0x10/0x10 [hid_universal_pidff 55b49ae4cd884535a75fc35c5a6e3d5760c319cb]
Jan 22 20:00:44 hephaestos kernel:  do_one_initcall+0x5b/0x310
Jan 22 20:00:44 hephaestos kernel:  do_init_module+0x60/0x230
Jan 22 20:00:44 hephaestos kernel:  init_module_from_file+0x89/0xe0
Jan 22 20:00:44 hephaestos kernel:  idempotent_init_module+0x11e/0x310
Jan 22 20:00:44 hephaestos kernel:  __x64_sys_finit_module+0x5e/0xb0
Jan 22 20:00:44 hephaestos kernel:  do_syscall_64+0x82/0x190
Jan 22 20:00:44 hephaestos kernel:  ? srso_return_thunk+0x5/0x5f
Jan 22 20:00:44 hephaestos kernel:  ? exc_page_fault+0x81/0x190
Jan 22 20:00:44 hephaestos kernel:  entry_SYSCALL_64_after_hwframe+0x76/0x7e
Jan 22 20:00:44 hephaestos kernel: RIP: 0033:0x715fa32621fd
Jan 22 20:00:44 hephaestos kernel: Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff>
Jan 22 20:00:44 hephaestos kernel: RSP: 002b:00007ffe70f2c2f8 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
Jan 22 20:00:44 hephaestos kernel: RAX: ffffffffffffffda RBX: 00005e7a7d100a10 RCX: 0000715fa32621fd
Jan 22 20:00:44 hephaestos kernel: RDX: 0000000000000004 RSI: 0000715fa29c94ac RDI: 0000000000000012
Jan 22 20:00:44 hephaestos kernel: RBP: 00007ffe70f2c3a0 R08: 00005e7a7d0dee60 R09: 00005e7a7cf04cb0
Jan 22 20:00:44 hephaestos kernel: R10: 00005e7a7d0dee90 R11: 0000000000000246 R12: 0000715fa29c94ac
Jan 22 20:00:44 hephaestos kernel: R13: 0000000000020000 R14: 0000000000000000 R15: 00005e7a7d0cd730
Jan 22 20:00:44 hephaestos kernel:  </TASK>
Jan 22 20:00:44 hephaestos kernel: Modules linked in: hid_universal_pidff(OE+) rfcomm snd_seq_dummy snd_seq_midi snd_hrtimer snd_seq_midi_event snd_seq uinput rpcrdma rdma_cm iw_cm ib_cm>
Jan 22 20:00:44 hephaestos kernel:  videobuf2_common aesni_intel snd_pcm realtek sp5100_tco gf128mul videodev crypto_simd mdio_devres snd_timer cryptd rfkill i2c_piix4 crc16 wmi_bmof rap>
Jan 22 20:00:44 hephaestos kernel: CR2: 0000000000000008
Jan 22 20:00:44 hephaestos kernel: ---[ end trace 0000000000000000 ]---
Jan 22 20:00:44 hephaestos kernel: RIP: 0010:universal_pidff_input_configured+0x26/0x80 [hid_universal_pidff]
Jan 22 20:00:44 hephaestos kernel: Code: 90 90 90 90 f3 0f 1e fa 0f 1f 44 00 00 55 45 31 c9 45 31 c0 53 48 8b 6e 18 31 f6 bb 01 00 00 00 48 8b 85 48 01 00 00 48 89 ef <8b> 48 08 8b 50 04>
Jan 22 20:00:44 hephaestos kernel: RSP: 0018:ffffa5668661b948 EFLAGS: 00010246
Jan 22 20:00:44 hephaestos kernel: RAX: 0000000000000000 RBX: 0000000000000001 RCX: ffff98b90bdf68a8
Jan 22 20:00:44 hephaestos kernel: RDX: ffff98b839ee1868 RSI: 0000000000000000 RDI: ffff98b90bdf6800
Jan 22 20:00:44 hephaestos kernel: RBP: ffff98b90bdf6800 R08: 0000000000000000 R09: 0000000000000000
Jan 22 20:00:44 hephaestos kernel: R10: 0000000000000000 R11: 0000000000000000 R12: ffff98ba08cec870
Jan 22 20:00:44 hephaestos kernel: R13: ffff98b839ee1840 R14: ffff98b839ee1840 R15: ffff98ba08cec000
Jan 22 20:00:44 hephaestos kernel: FS:  0000715fa38cb880(0000) GS:ffff98bb2ed00000(0000) knlGS:0000000000000000
Jan 22 20:00:44 hephaestos kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 22 20:00:44 hephaestos kernel: CR2: 0000000000000008 CR3: 000000036aba8000 CR4: 0000000000350ef0
Jan 22 20:00:44 hephaestos kernel: note: (udev-worker)[5142] exited with irqs disabled
```

### LINKED ISSUE #56: Null-pointer deref if optional HID reports are not present
From LKML:
https://lore.kernel.org/r/lkml/CAL-gK7f5=R0nrrQdPtaZZr1fd-cdAMbDMuZ_NLA8vM0SX+nGSw@mail.gmail.com/#t

When initializing a HID PID device, `hid-pidff.c` checks for eight required
HID reports and five optional reports. If the eight required reports are
present, the `hid_pidff_init()` function then attempts to find the necessary
fields in each required or optional report, using the `pidff_find_fields()`
function. However, if any of the five optional reports is not present,
`pidff_find_fields()` will trigger a null-pointer dereference.

I recently implemented the descriptors for a USB HID device with PID
force-feedback capability. After implementing the required report
descriptors but not the optional ones, I got an OOPS from the
`pidff_find_fields` function. I saved the OOPS from my Ubuntu installation,
and have attached it here. I later reproduced the issue on 6.11.6.

I was able to work around the issue by having my device present all of the
optional report descriptors as well as all of the required ones.

`Reported-by: Nolan Nicholson <nolananicholson@gmail.com>`

[trace.txt](https://github.com/user-attachments/files/18526355/trace.txt)

### PR DESCRIPTION
**Pull request by Lawstorant**
Compared to main:
Period rescaling
Updated clamping

`DEVICE_CONTROL` variable/array detection
Fixed reset, actuators modifications
Reset on effect uploads to an "empty" device, not just on init

Simplified `effect_upload` function
Moved some magic values to defines
Quirks renamed and repositioned
Clearer envelope check

Hid ids indented with tabs
Comment styling changes

Added support for LITE STAR GT978 FF
Closes #54 
Closes #56 

Test file changes:
Decrease magnitude of PERIODIC effects
Longer return spring

### CODE REVIEW

File: hid-ids.h [hunk 1]
```diff
@@ -3,38 +3,39 @@
...
-#define USB_DEVICE_ID_CAMMUS_C12    0x0302
+#define USB_VENDOR_ID_CAMMUS            0x3416
+#define USB_DEVICE_ID_CAMMUS_C5         0x0301
+#define USB_DEVICE_ID_CAMMUS_C12        0x0302
 
 // VRS DrivingForce Pro
-#define USB_VENDOR_ID_VRS           0x0483
-#define USB_DEVICE_ID_VRS_DFP       0xa355
+#define USB_VENDOR_ID_VRS	0x0483
+#define USB_DEVICE_ID_VRS_DFP	0xa355
```
Comment (JacKeTUs) [inline hid-ids.h:25]: Seems like alignment failed

File: hid-pidff-wrapper.c [hunk 2]
```diff
@@ -11,110 +12,51 @@
...
-		      unsigned int *rsize)
+static const u8 *moza_report_fixup(struct hid_device *hdev, __u8 *rdesc, unsigned int *rsize)
 {
-	// Fix data type on PID Device Control
-	if (rdesc[1002] == 0x91 && rdesc[1003] == 0x02) {
-		rdesc[1003] = 0x00; // Fix header, it needs to be Array.
-	}
+	/* Fix data type on PID Device Control */
+	if (rdesc[1002] == 0x91 && rdesc[1003] == 0x02)
+		rdesc[1003] = 0x00; /* Fix header, it needs to be Array. */
```
[the remark this answers is not in the document]
Comment (Lawstorant) [reply hid-pidff-wrapper.c:24]: I'll be honest, I don't even know if this still does anything. I'll chack later

File: hid-ids.h (hunk 1 above)
Comment (Lawstorant) [reply hid-ids.h:25]: No, this is actually good. Separate blocks should be aligned just to themselves. I think the Cammus one is actually misaligned as it seems to have an extra, unnecessary tab

File: hid-pidff-wrapper.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (Lawstorant) [reply hid-pidff-wrapper.c:24]: Yeah, it doesn't trigger anymore. Moza did some changes to the descriptor along with FFB3 update. Seems like leaving around noop is not a great idea so I'll remove this whole code block for now.

File: hid-ids.h (hunk 1 above)
Comment (Lawstorant) [reply hid-ids.h]: Indentation fixed

**Comment by Lawstorant** [comment]
Let me clean up the commits a little

**Comment by Lawstorant** [comment]
Moza ✅
PXN/Lite Star ✅
VRS not yet
Cammus not yet
FFBeast ✅
AccuForce ? (no explicit support in the driver)

**Comment by Lawstorant** [comment]
Closes #56
